const objectWithBlocks = [
    {
        type: "background",
        title: "hello",
        content: "this is a test text",
        color: "red",
        color2: "red"
    },
    {
        type: "header",
        title: "Header title",
        content: "this is a test text",
        buttonText: "klik",
        buttonUrl: "#",
        image: "",
        imgAlt: ""
    },
    {
        type: "imageText",
        title: "Image text block",
        content: "this is a test text",
        buttonText: "klik",
        buttonUrl: "#",
        image: "",
        imgAlt: "",
        textPosition: ""
    },
    {
        type: "install",
        title: "Image text block",
        content: "this is a test text",
        buttonText: "Image text block",
    },
    {
        type: "carHeader",
        title: "Car header title",
        subTitle: "Subtitle",
        content: "this is a test text",
        image: "",
        imgAlt: "",
        button1Text: "Image text block",
        button1Url: "",
        button2Text: "Image text block",
        button2Url: "",
        button3Text: "Image text block",
        button3Url: "",

    },
    {
        type: "contactForm",
        title: "Contact",
        nameValue: "Name",
        emailValue: "Email",
        messageValue: "Message",
        buttonValue: "Send email",
        image: "",
        imageAlt: "",
        yourEmail:"",
    },
    {
        type: "prices",
        title: "Prices",
        content: "We offer different prices based on the website you need. We plan a meeting to determent how match it gone cost.",
        block1Title: "Start",
        block1Price: "€200 - € 500",
        block1Content: "This type of website uses basic blocks in your style what you find in most websites. This website can be made in 3 days.",
        block2Title: "Medium",
        block2Price: "€500 - € 2500",
        block2Content: "This type of website uses basic blocks in your style what you find in most websites. This website can be made in 3 days.",
        block3Title: "Plus",
        block3Price: "€ 2500 +",
        block3Content: "This type of website uses basic blocks in your style what you find in most websites. This website can be made in 3 days.",
        contactButtonValue: "Get in contact",
        contactButtonLink: "#",
    },
    {
        title: "Website slider",
        type: "websiteSlider",
        block1Title: "Website name",
        block1Image: "",
        block1ImgAlt: "",
        block1Content: "Website content",
        block2Title: "Website name",
        block2Image: "",
        block2ImgAlt: "",
        block2Content: "Website content",
        block3Title: "Website name",
        block3Image: "",
        block3ImgAlt: "",
        block3Content: "Website content",
        object:{
            items: ["image","imgAlt"],
            item1: { 'image': 'hallo','imgAlt': 'hallo'  },
        },
    },
    {
        type: "header2",
        title: "title",
        subTitle: "Subtitle",
        content: "content",
        image: "",
        imgAlt: "",
        image2: "",
        imgAlt2: "",
        image3: "",
        imgAlt3: "",
        button1Text: "",
        button1Url: "",
        button2Text: "",
        button2Url: "",
        button3Text: "",
        button3Url: "",
        color1: "#ffffff",
        color2: "#ffffff",
        color3: "#ffffff",

    },
    {
        type: "imageTitle",
        title: "Title",
        text: "Text",
        image: "",
        imgAlt: "",
    },
];

export default objectWithBlocks;