name: Run JavaScript Function

on: [push]

jobs:
  run-function:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Run JavaScript Function
        run: node admin/fetchPages.js
