name: Generate HTML Pages

on: [push]

jobs:
  generate-html-pages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the desired Node.js version
        
      - name: Run JavaScript Function
        id: run-js
        run: node admin/fetchPages.js
        
      - name: Create HTML Pages
        run: |
          echo "Creating HTML pages"
          pages=${{ steps.run-js.outputs.stdout }}
          IFS=', ' read -ra pagesArray <<< "$pages"
          for page in "${pagesArray[@]}"; do
            lowercasePage=$(echo $page | tr '[:upper:]' '[:lower:]')
            filename="${lowercasePage}.html"
            content="<html><head><title>${page}</title></head><body><h1>${page}</h1></body></html>"
            echo "$content" > "$filename"
            echo "Created $filename"
          done
          
      - name: Commit and Push Changes
        run: |
          git config --global user.name "timmit147"
          git config --global user.email "timmeeuwsen@hotmail.nl"
          git add html-pages/
          git diff-index --quiet HEAD || git commit -m "Add generated HTML pages"
          git push origin HEAD:main
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
