name: Generate and Upload HTML Files

on:
  push:
    branches:
      - main

jobs:
  generate-html:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run JavaScript Function
      id: run-js
      run: |
        output=$(node admin/fetchPages.js)
        pages=$(echo "$output" | tr -d '[],"')
        formatted_pages=$(echo "$pages" | sed 's/ /\n/g')
        for page in $formatted_pages; do
          filename=$(echo "$page" | tr '[:upper:]' '[:lower:]').html
          echo "<html><head><title>$page</title></head><body><h1>$page</h1></body></html>" > "$GITHUB_WORKSPACE/$filename"
        done

    - name: Commit and Push Changes
      run: |
        git config --global user.name "timmit147"
        git config --global user.email "timmeeuwsen@hotmail.nl"
        git add .
        git diff-index --quiet HEAD || git commit -m "Add generated HTML pages"
        git push origin HEAD:main
