name: Generate and Upload HTML Files

on:
  push:
    branches:
      - main

jobs:
  generate-html:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run JavaScript Function
      id: run-js
      run: |
        output=$(node admin/fetchPages.js)
        pages=$(echo "$output" | jq -r '.[]')  # Assuming your output is in JSON array format

        # Assuming you're in the appropriate directory
        for page in $pages; do
          # Convert to lowercase and replace spaces with underscores in the filename
          filename=$(echo "$page" | tr '[:upper:]' '[:lower:]' | tr ' ' '_').html
          echo "<html><head><title>$page</title></head><body><h1>$page</h1></body></html>" > "$filename"
        done


    - name: Commit and Push Changes
      run: |
        git config --global user.name "timmit147"
        git config --global user.email "timmeeuwsen@hotmail.nl"
        git add .
        git diff-index --quiet HEAD || git commit -m "Add generated HTML pages"
        git push origin HEAD:main
