name: Generate and Push HTML Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run JavaScript Function
        id: run-js
        run: |
          page_names=$(node admin/fetchPages.js)
          echo "::set-output name=page_names::$page_names"

      - name: Create HTML Pages
        run: |
          page_names="${{ steps.run-js.outputs.page_names }}"
          for page in $page_names; do
            echo "<html><body><h1>${page}</h1></body></html>" > "${page}.html"
          done

      - name: Commit and Push Changes
        run: |
          git config --global user.name "timmit147"
          git config --global user.email "timmeeuwsen@hotmail.nl"
          git add .
          git diff-index --quiet HEAD || git commit -m "Add generated HTML pages"
          git push origin HEAD:main
