name: Run Firebase Fetch

on:
  push:
    branches:
      - main  # Change this to the appropriate branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run Firebase Fetch
      id: fetch
      run: node admin/fetchPages.js  # Replace with the actual filename

    - name: Show log output
      run: cat admin/output.log  # This assumes you're logging to a file named 'output.log'

    - name: Post Fetch Result as Comment
      if: steps.fetch.outcome == 'success'
      uses: actions/github-script@v4
      with:
        script: |
          const result = '${{ steps.fetch.outputs.result }}';
          const token = process.env.ACCESS_TOKEN;
          const octokit = new Octokit({ auth: token });

          // Get pull request number from the event payload
          const prNumber = context.payload.pull_request.number;

          // Create a comment with the fetch result
          await octokit.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: `Fetch Result: ${result}`,
          });