name: Build and Update Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Generate HTML pages
        run: node fetchDataCreatePage.js

      - name: Commit changes
        run: |
          git config user.name "timmit147"
          git config user.email "timmeeuwsen@hotmail.nl"
          git add .
          git commit -m "Update HTML pages"

      - name: Pull and push
        run: |
          git pull origin main
          git push
