name: Fetch and Display Firebase Page Names

on:
  push:
    branches:
      - main

jobs:
  fetch-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Fetch and Display Pages
        run: node admin/fetchPages.js

      - name: Display output
      run: cat admin/output.json # Assuming you're saving the output in a file named "output.json"
